Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -30,8 +30,12 @@ runs:
           | jq -c '.[] | select(.name | contains("'${BRANCH_NAME}'")) .id' \
           | jq -r \
           ) \
-
+        if [ -z "$branch_id" ]; then
+          echo "Error: branch_id is empty." >&2
+          exit 1
+        fi
         echo "branch_id=${branch_id}" >> $GITHUB_OUTPUT
+        
       env:
         PROJECT_ID: ${{ inputs.project_id }}
         API_KEY: ${{ inputs.api_key }}
